CREATE TABLE BOOK(
	[ID] INTEGER IDENTITY(1,1),
	[TITLE] VARCHAR(50) NOT NULL,
	[AUTHOR] VARCHAR(50) NOT NULL,
	[YEAR] INTEGER,
	[QUANTITY] INTEGER DEFAULT 0,

	PRIMARY KEY([ID])
);

CREATE TABLE READER(
	[ID] INTEGER IDENTITY(1,1),
	[NAME] VARCHAR(30),
	[SURNAME] VARCHAR(30),
	[DATE OF BIRTH] DATE,

	PRIMARY KEY([ID])
);

CREATE TABLE RENTALS(
	[BOOK ID] INTEGER REFERENCES BOOK(ID),
	[READER] INTEGER REFERENCES READER(ID),

	PRIMARY KEY([BOOK ID], [READER])
);
GO
CREATE VIEW BOOK_RENTALS_COMPLETE AS 
SELECT BOOKRENTALS.TITLE, BOOKRENTALS.AUTHOR, CONCAT(READER.NAME, ' ', READER.SURNAME) "RENTED BY" 
FROM READER INNER JOIN (SELECT BOOK.TITLE, BOOK.AUTHOR, RENTALS.READER 
	FROM BOOK INNER JOIN RENTALS ON dbo.Book.ID = dbo.Rentals.[BOOK ID]) BOOKRENTALS
ON READER.ID = BOOKRENTALS.READER;